version: '3'

vars:
  GREETING: Hello, World!
  BACKEND_EXE: review-app.exe
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build-backend:
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go build -o ../{{.BACKEND_EXE}} ./cmd/main.go
    sources:
      - ./cmd/**/*.go
      - go.mod
      - go.sum
    generates:
      - ../{{.BACKEND_EXE}}

  run-backend:
    deps: [build-backend]
    cmds:
      - ./{{.BACKEND_EXE}}

  run-frontend:
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm start

  run:
    deps:
      - run-backend
      - run-frontend

  clean:
    cmds:
      - rm -f {{.BACKEND_EXE}}